SOS/urls.py
from filebrowser.sites import site

from django.conf.urls import patterns, include, url
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	url(r'^grappelli/', include('grappelli.urls')),
	url(r'^admin/filebrowser/', include(site.urls)),
	url(r'^admin/', include(admin.site.urls)),
	url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
)

urlpatterns += patterns('cms.views',
	url(r'^(?P<language>[a-z]{2,3})/news/(?P<date>\d{4}/[a-z]{3}/\d{2})/(?P<slug>(\w|-)+).html$', 'show_entry'),
	url(r'^(?P<language>[a-z]{2,3})/news/(?P<year>\d{4})/(?P<month>[a-z]{3})/$', 'archive'),
	url(r'^(?P<language>[a-z]{2,3})/news/(?P<year>\d{4})/$', 'archive'),
	url(r'^(?P<language>[a-z]{2,3})/news/$', 'archive'),
	url(r'^(?P<language>[a-z]{2,3})/search$', 'search'),
	url(r'^(?P<language>[a-z]{2,3})/(?P<slug>(\w|-)+).html$', 'show_page'),
	url(r'^(?P<language>[a-z]{2,3})/$', 'index'),
	url(r'^$', 'index'),
)

cms/models.py
from filebrowser.fields import FileBrowseField
from django.db import models

class Language(models.Model):
	small_name = models.CharField(max_length=3)
	long_name = models.CharField(max_length=20)

	def __unicode__(self):
		return self.small_name

	def get_absolute_url(self):
		return '/%s' % self.small_name

class Page(models.Model):
	language = models.ForeignKey('Language')
	
	title = models.CharField(max_length=50)
	slug = models.SlugField()
	body = models.TextField()

	# optional fields
	parent = models.ForeignKey('self', blank=True, null=True)
	priority = models.IntegerField(blank=True, null=True)
	url = models.CharField(max_length=200, blank=True, null=True)

	def __unicode__(self):
		return self.title

	class Meta:
		ordering = ['priority']

	def get_absolute_url(self):
		if self.url:
			return self.url
		else:
			return '/%s/%s.html' % (self.language, self.slug)

class Entry(models.Model):
	language = models.ForeignKey('Language')

	title = models.CharField(max_length=50)
	slug = models.SlugField()
	body = models.TextField()

	# optional
	image = FileBrowseField("Image", max_length=200, directory="images/", blank=True, null=True)

	date_published = models.DateTimeField()

	def __unicode__(self):
		return self.title

	class Meta:
		verbose_name_plural = "entries"
		ordering = ['-date_published']

	def get_absolute_url(self):
		return '/%s/news/%s/%s.html' % (
				self.language,
				self.date_published.strftime("%Y/%b/%d").lower(),
				self.slug,
			)

cms/views.py
from datetime import datetime

from cms.models import Language, Page, Entry

from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render_to_response
from django.db.models import Q

def index(request, language='az'):
	language = get_object_or_404(Language, small_name=language)

	return render_to_response('index.html', {
				'current_language': language,
				'languages': Language.objects.all(),
				'top_links': Page.objects.filter(language=language, parent=None)[:5],
				'bottom_links': Page.objects.filter(language=language, parent=None)[5:8],
				'side_links': Page.objects.filter(language=language, parent=None)[8:],
				'latest_entries': Entry.objects.filter(language=language).exclude(image=None)[:3],
			})

def show_page(request, language, slug):
	language = get_object_or_404(Language, small_name=language)
	page = get_object_or_404(Page, slug=slug, language=language)

	return render_to_response('show_page.html', {
				'current_language': language,
				'languages': Language.objects.all(),
				'top_links': Page.objects.filter(language=language, parent=None)[:5],
				'bottom_links': Page.objects.filter(language=language, parent=None)[5:8],
				'side_links': Page.objects.filter(language=language, parent=None)[8:],
				'latest_entries': Entry.objects.filter(language=language).exclude(image=None)[:3],
				'page': page,
			})

def show_entry(request, language, date, slug):
	language = get_object_or_404(Language, small_name=language)
	date = datetime.strptime(date, "%Y/%b/%d")

	entry = get_object_or_404(Entry,
			language=language,
			date_published__year=date.year,
			date_published__month=date.month,
			date_published__day=date.day,
			slug=slug
		)

	return render_to_response('show_entry.html', {
				'current_language': language,
				'languages': Language.objects.all(),
				'top_links': Page.objects.filter(language=language, parent=None)[:5],
				'bottom_links': Page.objects.filter(language=language, parent=None)[5:8],
				'side_links': Page.objects.filter(language=language, parent=None)[8:],
				'latest_entries': Entry.objects.filter(language=language).exclude(image=None)[:3],
				'entry': entry,
			})

def archive(request, language, year=None, month=None):
	language = get_object_or_404(Language, small_name=language)
	
	if year and month:
		date = datetime.strptime(year + "/" + month, "%Y/%b")
		entries = Entry.objects.filter(
				language=language,
				date_published__year=date.year,
				date_published__month=date.month,
			)
		year_range = None
	elif year:
		date = datetime.strptime(year, "%Y")
		entries = Entry.objects.filter(
				language=language,
				date_published__year=date.year,
			)
		year_range = None
	else:
		first_date = Entry.objects.all().reverse()[0].date_published
		last_date = Entry.objects.all()[0].date_published
		year_range = range(first_date.year, last_date.year + 1)
		entries = []
		date = datetime.now()

	return render_to_response('archive.html', {
				'current_language': language,
				'languages': Language.objects.all(),
				'top_links': Page.objects.filter(language=language, parent=None)[:5],
				'bottom_links': Page.objects.filter(language=language, parent=None)[5:8],
				'side_links': Page.objects.filter(language=language, parent=None)[8:],
				'entries': entries,
				'year': date.year,
				'month': date.strftime("%B") if month else '',
				'year_range': year_range,
			})

def search(request, language):
	language = get_object_or_404(Language, small_name=language)
	
	query = request.GET['q']

	entries = Entry.objects.filter(
			Q(title__icontains=query) |
			Q(body__icontains=query)
		)

	pages = Page.objects.filter(
			Q(title__icontains=query) |
			Q(body__icontains=query)
		)

	return render_to_response('search.html', {
				'current_language': language,
				'languages': Language.objects.all(),
				'top_links': Page.objects.filter(language=language, parent=None)[:5],
				'bottom_links': Page.objects.filter(language=language, parent=None)[5:8],
				'side_links': Page.objects.filter(language=language, parent=None)[8:],
				'entries': entries,
				'pages': pages,
				'query': query,
			})

SOS/templates/archive.html
{% extends "base.html" %}

{% block title %}Archive for {{ month }} {{ year }} - {% endblock %}

{% block content %}
	{% if year_range %}
	<h4>Select year</h4>
	<ul>
	{% for year in year_range %}
		<li><a href="{{ year }}">{{ year }}</a></li>
	{% endfor %}
	</ul>
	{% else %}
	<h4>Results for {{ month }} {{ year }}</h4>
	<ul>
	{% for entry in entries %}
		<li><a href="{{ entry.get_absolute_url }}">{{ entry }}</a> on {{ entry.date_published|date:"M j, Y" }}</li>
	{% empty %}
		<li>Sorry, no results...</li>
	{% endfor %}
	</ul>
	{% endif %}
{% endblock %}

SOS/templates/base.html
{% load staticfiles %}
<!DOCTYPE HTML>
<html>
<meta charset="utf-8" />
<head>
	<title>{% block title %}{% endblock %}SOS Children Azerbaijan</title>

	<link rel="icon" type="image/png" href="{% static "img/favicon.png" %}" />

	<link href="http://netdna.bootstrapcdn.com/twitter-bootstrap/2.2.2/css/bootstrap-combined.min.css" rel="stylesheet">
	<link href="{% static "css/jquery.tweet.css" %}" rel="stylesheet" />
	<link href="{% static "css/sharrre.css" %}" rel="stylesheet" />
	<link href="{% static "css/main.css" %}" rel="stylesheet" />

	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
	<script src="http://netdna.bootstrapcdn.com/twitter-bootstrap/2.2.2/js/bootstrap.min.js"></script>
	<script type="text/javascript" src="{% static "js/jquery.tweet.js" %}"></script>
	<script type="text/javascript" src="{% static "js/jquery.sharrre-1.3.4.min.js" %}"></script>
	<script type="text/javascript" src="{% static "js/scripts.js" %}"></script>
</head>
<body>
	<div class="top-back-back"></div>
	<div class="top-back">
		<header>
			<a href="/{{ current_language }}" class="logo"></a>
			<div class="social-logos">
				<a href="#" class="facebook-link"></a>
				<a href="#" class="twitter-link"></a>
			</div>
			<div class="header-text">
				<span>Welcome to SOS Children Azerbaijan |</span>
				{% for language in languages %}
					<a{% ifequal language current_language %} class="disabled"{% endifequal %} href="{{ language.get_absolute_url }}">{{ language|upper }}</a>
				{% endfor %}
			</div>
		</header>
	</div>
	<div class="wrapper">
		<div class="cover"></div>
		<div class="navigation">
			<a href="/{{ current_language }}" class="nav-home"></a>
			<nav>
				<ul>
				{% for link in top_links %}
					<li><a href="{{ link.get_absolute_url }}">{{ link }}</a>
					{% if link.page_set.all %}
						<ul>
						{% for sub_link in link.page_set.all %}
							<li><a href="{{ sub_link.get_absolute_url }}">{{ sub_link }}</a></li>
						{% endfor %}
						</ul>
					{% endif %}
				{% endfor %}
				</ul>
			</nav>
			<form action="/{{ current_language }}/search" method="get" class="nav-search">
				<input type="search" name="q" placeholder="Search..." required="required" value="{{ query }}" />
			</form>
		</div>
		{% block menubox %}{% endblock %}
		<div class="content">
			{% block content %}{% endblock %}
		</div>
		<div class="big-links">
			<a href="#" class="big-donate">{% if current_language.small_name == "az" %}İanə edin{% else %}Donate now{% endif %}</a>
			<a href="#" class="big-contactus">{% if current_language.small_name == "az" %}Əlaqə{% else %}Contact us{% endif %}</a>
			<a href="#" class="big-plans">{% if current_language.small_name == "az" %}Planlar və hesabatlar{% else %}Plans and reports{% endif %}</a>
			<a href="#" class="big-advert">{% if current_language.small_name == "az" %}Reklamlar{% else %}Adverstisements{% endif %}</a> 
		</div>
		<footer>
			<div class="twitter-wrapper">
				<a href="#" class="twitter-user">@SOSChildrenAz</a>
				<div class="tweet"></div>
			</div>
			<div class="share-buttons">
				<div id="shareme" data-text="SOS Children Azerbaijan"></div>
			</div>
			<div class="footer-text">
				<p>SOS Children`s Villages Azerbaijan Registration Certificate #1180 | Registration date - 15.10.1999 | ID#3137826 | TIN: 1400593081</p>
				<p>Account: 33308019449722421207 | Azerbaijan International Bank, Nasimi Branch | Code: 805614 | Bank TIN: 9900001881</p>
				<p>S.W.I.F.T.BIK: İBAZAZ2X | Correspondent account: AZ03NABZ01350100000000002944</p>
				<p>Address: Dilara Aliyeva 251A, AZ1010, Baku, Azerbaijan | +994124890296/97 | info[at]soschildren.az</p>
			</div>
			<small>{% now "Y" %} &copy; SOS Children Villages Azerbaijan</small>
		</footer>
	</div>
	<div class="footer-back"></div>
	<div style="display: none"><img src="http://soschildrenaz.ismayilov.info/static/img/logo.gif" alt="" /></div>
</body>
</html>

SOS/templates/index.html
{% extends "base.html" %}

{% load staticfiles %}
{% block content %}
<div id="myCarousel" class="carousel slide">
	<!-- Carousel items -->
	<div class="carousel-inner">
		{% for entry in latest_entries %}
		<div class="item{% if forloop.first %} active{% endif %}">
			<img src="{{ entry.image.url }}" alt="{{ entry }}" />
			<div class="carousel-caption">
				<h4><a href="{{ entry.get_absolute_url }}">{{ entry }}</a></h4>
				<time>{{ entry.date_published|date:"M j, Y" }}</time>
			</div>
		</div>
		{% endfor %}
	</div>
	<!-- Carousel nav -->
	<a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
	<a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div>
{% endblock %}

SOS/templates/search.html
{% extends "base.html" %}

{% block title %}Results for {{ query }} - {% endblock %}

{% block content %}
<div class="container-fluid">
	<h4>Results for "{{ query }}"</h4>
	<div class="row-fluid">
		<div class="span6">
			<h5>Entries</h5>
			<ul>
			{% for entry in entries %}
				<li><a href="{{ entry.get_absolute_url }}">{{ entry }}</a> on {{ entry.date_published|date:"M j, Y" }}</li>
			{% empty %}
				<li>Sorry, no results...</li>
			{% endfor %}
			</ul>
		</div>
		<div class="span6">
			<h5>Pages</h5>
			<ul>
			{% for page in pages %}
				<li><a href="{{ page.get_absolute_url }}">{{ page }}</a></li>
			{% empty %}
				<li>Sorry, no results...</li>
			{% endfor %}
			</ul>
		</div>
	</div>
</div>
{% endblock %}

SOS/templates/show_entry.html
{% extends "base.html" %}

{% block title %}{{ entry.title }} - {% endblock %}

{% block content %}
	<img src="{{ entry.image.url }}" alt="{{ entry }}" width="{{ entry.image.width }}" height="{{ entry.image.height }}" />
	<h4>{{ entry.title }}</h4>
	<time>{{ entry.date_published|date:"d.m.Y" }}</time>
	<div>{{ entry.body|safe }}</div>
{% endblock %}

SOS/templates/show_page.html
{% extends "base.html" %}

{% block title %}{{ page.title }} - {% endblock %}

{% block menubox %}
	{% if page.page_set.all and page.parent %}
		<div class="menu-box">
			<div class="menu-box-left"></div>
		{% for child_page in page.page_set.all %}
			<a href="{{ child_page.get_absolute_url }}">{{ child_page }}</a>
			{% if forloop.last %}{% else %}
			<span>|</span>
			{% endif %}
		{% endfor %}
		<div class="menu-box-right"></div>
	</div>
	{% elif page.parent %}
		<div class="menu-box">
			<div class="menu-box-left"></div>
		{% for child_page in page.parent.page_set.all %}
			<a href={{ child_page.get_absolute_url }}{% ifequal child_page page %} class="menubox-active"{% endifequal %}>{{ child_page }}</a>
			{% if forloop.last %}{% else %}
			<span>|</span>
			{% endif %}
		{% endfor %}
		<div class="menu-box-right"></div>
	</div>
	{% endif %}
{% endblock %}

{% block content %}
	<h4>{{ page.title }}</h4>
	{{ page.body|safe }}
{% endblock %}